cache:
  paths:
    - .m2/

before_script:
   - export MAVEN_OPTS="-Dmaven.repo.local=${PWD}.m2"

test:
  script:
    - mvn --batch-mode test

javadoc:
  script:
    - mvn --batch-mode javadoc:javadoc
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    expire_in: 12 weeks
    paths:
    - target/site/apidocs/
